runserver:
		 @ python manage.py runserver 5000
migrations:
		 @ python manage.py makemigrations
migrate:
		@python manage.py migrate


accountsmigrations:
		 @python manage.py makemigrations
accountsmigrate:
		@python manage.py migrate


blogmigrations:
		 @python manage.py makemigrations
blogmigrate:
		@python manage.py migrate