# Generated by Django 5.0.8 on 2024-08-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('other', 'Other')], max_length=50),
        ),
    ]
